services:
  frontend:
    image: ghcr.io/yuqi1991/sub-web-modify:latest
    container_name: sub-web-modify-frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    ports:
      - "15051:25500"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
