services:
  frontend:
    image: ghcr.io/yuqi1991/sub-web-modify:latest
    container_name: sub-web-modify-frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    image: ghcr.io/yuqi1991/subconverter:latest
    container_name: subconverter
    ports:
      - "15051:25500"
    restart: unless-stopped
    network_mode: host
    # 如果需要访问宿主机的配置文件，使用 --add-host
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
